import path from 'path';
import fs from 'fs/promises';
import type { ScreenshotCapture } from '../core/types';

/**
 * Generate an HTML gallery page for captured screenshots
 */
export async function generateGallery(
  captures: ScreenshotCapture[],
  outputDir: string,
  demoName: string
): Promise<string> {
  const screenshotCards = captures
    .map((capture, index) => generateScreenshotCard(capture, index + 1))
    .join('\n    ');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(demoName)} - Screenshots</title>
  <style>
    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
      background: #1a1a2e;
      color: #fff;
      padding: 40px;
      min-height: 100vh;
    }

    header {
      text-align: center;
      margin-bottom: 40px;
    }

    h1 {
      font-size: 2.5rem;
      font-weight: 700;
      margin-bottom: 8px;
    }

    .subtitle {
      color: #888;
      font-size: 1.1rem;
    }

    .gallery {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(450px, 1fr));
      gap: 24px;
      max-width: 1800px;
      margin: 0 auto;
    }

    .screenshot {
      background: #16213e;
      border-radius: 12px;
      overflow: hidden;
      transition: transform 0.2s ease, box-shadow 0.2s ease;
    }

    .screenshot:hover {
      transform: translateY(-4px);
      box-shadow: 0 12px 40px rgba(0, 0, 0, 0.4);
    }

    .screenshot a {
      display: block;
    }

    .screenshot img {
      width: 100%;
      display: block;
      border-bottom: 1px solid #0f3460;
    }

    .meta {
      padding: 16px 20px;
    }

    .action {
      color: #4285f4;
      font-weight: 600;
      font-size: 1rem;
      margin-bottom: 4px;
    }

    .selector {
      color: #888;
      font-size: 0.85rem;
      font-family: 'SF Mono', Monaco, Consolas, monospace;
      word-break: break-all;
    }

    .timestamp {
      color: #555;
      font-size: 0.75rem;
      margin-top: 8px;
    }

    footer {
      text-align: center;
      margin-top: 60px;
      padding-top: 20px;
      border-top: 1px solid #16213e;
      color: #555;
      font-size: 0.85rem;
    }

    footer a {
      color: #4285f4;
      text-decoration: none;
    }

    @media (max-width: 600px) {
      body {
        padding: 20px;
      }

      .gallery {
        grid-template-columns: 1fr;
      }

      h1 {
        font-size: 1.8rem;
      }
    }
  </style>
</head>
<body>
  <header>
    <h1>${escapeHtml(demoName)}</h1>
    <p class="subtitle">${captures.length} screenshot${captures.length !== 1 ? 's' : ''} captured</p>
  </header>

  <div class="gallery">
    ${screenshotCards}
  </div>

  <footer>
    Generated by <a href="https://github.com/neonwatty/demo-recorder" target="_blank">demo-recorder</a>
  </footer>
</body>
</html>`;

  const galleryPath = path.join(outputDir, 'gallery.html');
  await fs.writeFile(galleryPath, html, 'utf-8');

  return galleryPath;
}

/**
 * Generate HTML for a single screenshot card
 */
function generateScreenshotCard(capture: ScreenshotCapture, index: number): string {
  const actionLabel = getActionLabel(capture.action);
  const timestamp = new Date(capture.timestamp).toLocaleTimeString();

  return `<div class="screenshot">
      <a href="${escapeHtml(capture.filename)}" target="_blank">
        <img src="${escapeHtml(capture.filename)}" alt="Screenshot ${index}" loading="lazy">
      </a>
      <div class="meta">
        <div class="action">${index}. ${escapeHtml(actionLabel)}</div>
        ${capture.selector ? `<div class="selector">${escapeHtml(capture.selector)}</div>` : ''}
        <div class="timestamp">${escapeHtml(timestamp)}</div>
      </div>
    </div>`;
}

/**
 * Get human-readable action label
 */
function getActionLabel(action?: string): string {
  switch (action) {
    case 'click':
      return 'Click';
    case 'type':
      return 'Type';
    case 'highlight':
      return 'Highlight';
    case 'scroll':
      return 'Scroll';
    case 'manual':
      return 'Manual Capture';
    default:
      return action || 'Screenshot';
  }
}

/**
 * Escape HTML special characters
 */
function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
