import path from 'path';
import fs from 'fs/promises';
import type { ScreenshotCapture } from '../core/types';

export interface MarkdownOptions {
  /** Title for the markdown document */
  title?: string;
  /** Description/intro paragraph */
  description?: string;
  /** Whether to use relative paths for images (default: true) */
  relativePaths?: boolean;
  /** Include timestamps (default: false) */
  includeTimestamps?: boolean;
  /** Include selectors in code blocks (default: false) */
  includeSelectors?: boolean;
}

/**
 * Generate markdown documentation from captured screenshots
 */
export async function generateMarkdown(
  captures: ScreenshotCapture[],
  outputDir: string,
  demoName: string,
  options: MarkdownOptions = {}
): Promise<string> {
  const {
    title = demoName,
    description,
    relativePaths = true,
    includeTimestamps = false,
    includeSelectors = false,
  } = options;

  const lines: string[] = [];

  // Header
  lines.push(`# ${title}`);
  lines.push('');

  if (description) {
    lines.push(description);
    lines.push('');
  }

  lines.push(`> ${captures.length} step${captures.length !== 1 ? 's' : ''} in this walkthrough`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Generate steps
  for (let i = 0; i < captures.length; i++) {
    const capture = captures[i];
    const stepNum = i + 1;
    const actionLabel = getActionLabel(capture.action);

    // Step header
    lines.push(`## Step ${stepNum}: ${actionLabel}`);
    lines.push('');

    // Image
    const imagePath = relativePaths
      ? capture.filename
      : capture.filepath;
    lines.push(`![Step ${stepNum} - ${actionLabel}](${imagePath})`);
    lines.push('');

    // Selector info
    if (includeSelectors && capture.selector) {
      lines.push('**Target element:**');
      lines.push('```css');
      lines.push(capture.selector);
      lines.push('```');
      lines.push('');
    }

    // Timestamp
    if (includeTimestamps) {
      const timestamp = new Date(capture.timestamp).toLocaleTimeString();
      lines.push(`*Captured at ${timestamp}*`);
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // Footer
  lines.push('');
  lines.push('*Generated by [demo-recorder](https://github.com/neonwatty/demo-recorder)*');

  const markdown = lines.join('\n');
  const markdownPath = path.join(outputDir, 'walkthrough.md');
  await fs.writeFile(markdownPath, markdown, 'utf-8');

  return markdownPath;
}

/**
 * Generate markdown from an existing screenshot directory
 */
export async function generateMarkdownFromDirectory(
  screenshotDir: string,
  options: MarkdownOptions = {}
): Promise<string> {
  const files = await fs.readdir(screenshotDir);
  const screenshotFiles = files
    .filter(f => /^screenshot-\d+.*\.(png|jpe?g|webp)$/i.test(f))
    .sort();

  if (screenshotFiles.length === 0) {
    throw new Error(`No screenshots found in ${screenshotDir}`);
  }

  // Build captures from filenames
  const captures: ScreenshotCapture[] = screenshotFiles.map((filename, index) => {
    // Parse action from filename: screenshot-001-click-1.png
    const match = filename.match(/screenshot-\d+-([a-z]+)/i);
    const action = match ? match[1] : undefined;

    return {
      filepath: path.join(screenshotDir, filename),
      filename,
      timestamp: Date.now() - (screenshotFiles.length - index) * 1000,
      action,
    };
  });

  const demoName = options.title || path.basename(screenshotDir);
  return generateMarkdown(captures, screenshotDir, demoName, options);
}

/**
 * Get human-readable action label
 */
function getActionLabel(action?: string): string {
  switch (action) {
    case 'click':
      return 'Click';
    case 'type':
      return 'Type text';
    case 'highlight':
      return 'Highlight element';
    case 'scroll':
      return 'Scroll';
    case 'manual':
      return 'Screenshot';
    default:
      return action ? capitalizeFirst(action) : 'Action';
  }
}

function capitalizeFirst(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
